alias python='/home/vagrant/uber/sideboard/env/bin/python3'
export PYTHONSTARTUP='/home/vagrant/uber/vagrant/pythonstartup.py'
alias run_server='/home/vagrant/uber/sideboard/env/bin/python3 /home/vagrant/uber/sideboard/sideboard/run_server.py'

source /home/vagrant/uber/sideboard/env/bin/activate
